### ISSUE TITLE
on new macOS 10.14 does not work

### ISSUE THREAD

**Issue by yarodevuci** [smallmuou/ios-icon-generator#21]
I am getting this error: 
-e [ERROR] The ImageMagick is not installed. Please use brew to install it first.

However I already install ImageMagick

Anything i can try

**Comment by smallmuou** [comment]
Please check `convert` command if exist.

**Comment by smallmuou** [comment]
Just now, it release v2.0.0 script to run without ImageMagick. and it support iOS/macOS/watchOS app at the same time. Looking forward to your use.
